collections:
  posts:
    output: true
    label: Blog Posts
    folder: _posts
    create: true
    fields:
      - name: title
        label: Title
        type: text
      - name: date
        label: Date
        type: datetime
      - name: categories
        label: Categories
        type: list
      - name: tags
        label: Tags
        type: list
      - name: excerpt
        label: Excerpt
        type: textarea
      - name: image
        label: Image
        type: text
      - name: content
        label: Content
        type: markdown
        default: ""
